---
- name: Install brew packages
  community.general.homebrew:
    name:
      - eza
      - fd
      - ripgrep
      - bat
      - ccat
      - direnv
      - jc
      - jq
      - yq
      - delta
      - keychain
    state: present

- name: Setup gitconfig
  file:
    src: gitconfig.ini
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    mode: "0644"
    force: true

- name: Setup theming directories where the themes will be installed
  include_tasks: theme_dirs.yml

- name: Install nerd fonts for code editing
  include_tasks: nerd_fonts.yml

- name: Install KDE Plasma themes if its being used
  include_tasks: install_kde_plasma_themes.yml
  when: "'GNOME' in (ansible_env.XDG_CURRENT_DESKTOP | default(''))
        or 'gnome' in (ansible_env.XDG_CURRENT_DESKTOP | default(''))"

- name: Install Gnome themes if its being used
  include_tasks: install_gnome_themes.yml
  when: "'KDE' in (ansible_env.XDG_CURRENT_DESKTOP | default(''))
        or 'plasma' in (ansible_env.XDG_CURRENT_DESKTOP | default(''))"

- name: Setup hyprland config and its related tooling dotfiles
  include_tasks: setup_hyprland.yml
  when: "'Hyprland' in (ansible_env.XDG_CURRENT_DESKTOP | default(''))
        or 'hyprland' in (ansible_env.XDG_CURRENT_DESKTOP | default(''))"

- name: Setup fish shell
  include_tasks: fish.yml

- name: Setup starship prompt
  include_tasks: starship.yml

- name: Setup neovim
  include_tasks: nvim.yml

- name: Setup tmux
  include_tasks: tmux.yml

- name: Setup rfcv
  include_tasks: rfcv.yml

- name: Install k3s
  include_tasks: k3s.yml
