---
- name: Download k3s install script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s_install.sh
    mode: "0755"

- name: Install k3s
  command: sh /tmp/k3s_install.sh
  args:
    creates: /usr/local/bin/k3s

- name: Enable k3s service
  systemd:
    name: k3s
    state: started
    enabled: yes
